# Simple shortcuts and magics

In [1]:
#Установим библиотеку для отрисовки графиков, если её у вас нет
!pip install matplotlib
!pip install Flask

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
#Magic, который пишем чаще всего. Что он делает?
#import numpy
#import matplotlib
#from matplotlib import pylab, mlab, pyplot
#np = numpy
#plt = pyplot
#from IPython.display import display
#from IPython.core.pylabtools import figsize, getfigs
#from pylab import *
#from numpy import *

#и все это 1 строчкой! inline указывает, что вывод графиков будет в ноутбук (подробнее в документации: выбор движка)
%pylab inline

/home/irina/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py:278: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '


Populating the interactive namespace from numpy and matplotlib


In [3]:
%%writefile hello.py
#Найдите magic, который записывает значение ячейки в файл. Создайте модуль hello.py, импортируйте из него hello_world
def hello_world():
    print("hello")

Writing hello.py


In [6]:
%%time
#Засеките время выполнения процедуры с помощью magic
def count(start=0, end=10000):
    for _ in range(start, end):
        continue
count()

CPU times: user 776 µs, sys: 134 µs, total: 910 µs
Wall time: 817 µs


In [13]:
from hello import hello_world
hello_world()

hello


In [ ]:
#Объедините эту ячейку и ячейку ниже с помощью shortcut
def very_important_function():
    start="end"

    fucing_cat="change the cell"

In [14]:
#Исправьте все хождения value в ячейке на name
cat="cat_1"
cat_cat="cat_cat_2"

In [15]:
cat

'cat_1'

In [9]:
#Содержание ячейки, запущенной второй
print(In[2])

#Magic, который пишем чаще всего. Что он делает?
#import numpy
#import matplotlib
#from matplotlib import pylab, mlab, pyplot
#np = numpy
#plt = pyplot
#from IPython.display import display
#from IPython.core.pylabtools import figsize, getfigs
#from pylab import *
#from numpy import *

#и все это 1 строчкой! inline указывает, что вывод графиков будет в ноутбук (подробнее в документации: выбор движка)
get_ipython().run_line_magic('pylab', 'inline')


# Numpy

In [16]:
#Импортируем модуль
import numpy as np

In [17]:
#Создадим всякие массивчики
string_array = np.array(["строка", 5])
float_array = np.array([5., 5])
float_array_2 = np.array([6.])
int_array = np.array([5, 4])
two_dimarray = np.array([[5, 4], [4, 6]])
one_dimarray = np.array([[5, 4], [4]])

In [ ]:
#К массивам можно обращаться по 2 индексам. Возможны срезу по нескольким осям
example_list = [[5, 4], [7, 8]]
example_list[:, 1]

In [ ]:
example_arr = np.array([[5, 4], [7, 8]])
example_arr[:, 1]

In [18]:
#Можно получить параметры массива: тип данных, форму, размерность вдоль оси
two_dimarray = np.array([[5, 4], [4, 6]])
print("Размерность вдоль первой оси: {}".format(len(two_dimarray)))
print("Размерность массива: {}".format(two_dimarray.shape))
print("Тип данных в массиве: {}".format(two_dimarray.dtype))

#Давайте пожмем наш int64 до int8 (преподложим, что знаем ограничение на размер чисел)
import sys
print("Размер исходного массива %d" % sys.getsizeof(two_dimarray))
two_dimarray = two_dimarray.astype(np.int8)
print("Размер массива после преобразования %d" % sys.getsizeof(two_dimarray))

Размерность вдоль первой оси: 2
Размерность массива: (2, 2)
Тип данных в массиве: int64
Размер исходного массива 144
Размер массива после преобразования 116


In [19]:
oneses = np.ones(3)
zeros = np.zeros(4)
print(oneses)
print(zeros)

[1. 1. 1.]
[0. 0. 0. 0.]


In [21]:
def simple_matrix_generator(n):
    #TODO создать единичную матрицу размера n x n в виде numpy array
    one=np.identity(n)
    return one

In [22]:
assert np.array_equal(simple_matrix_generator(4), np.array([[1., 0., 0., 0.], [0., 1., 0., 0.], [0., 0., 1., 0.], [0., 0., 0., 1.]]))
assert np.array_equal(simple_matrix_generator(3), np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]))
assert np.array_equal(simple_matrix_generator(2), np.array([[1., 0.], [0., 1.]]))

In [23]:
#Преобразование формы массива 
example = np.array([5, 4, 7, 8])
print(example)
print(example.reshape(2, 2))
print(example.reshape(2, 2).flatten())

[5 4 7 8]
[[5 4]
 [7 8]]
[5 4 7 8]


In [24]:
# Массивы можно по-разному объединять и добавлять элементы
example = np.array([5., 6.])
example = np.append(example, example)
print(example)
example = np.array([[5.], [6.]])
print(np.concatenate((example, example), axis=0))
print(np.concatenate((example, example), axis=1))
print(np.vstack((example, example)))
print(np.hstack((example, example)))

[5. 6. 5. 6.]
[[5.]
 [6.]
 [5.]
 [6.]]
[[5. 5.]
 [6. 6.]]
[[5.]
 [6.]
 [5.]
 [6.]]
[[5. 5.]
 [6. 6.]]


In [25]:
#Над массивами numpy можно производить простейшие математические операции
example = np.array([5, 4, 7, 8])
print(example / 2)
print(example * 3)
print(example + 32)
print(example - 1)
print(example ** 2)
print("Multidemensional")
example = np.array([[5, 4], [7, 8]])
print(example / 2)
print(example * 3)
print(example + 32)
print(example - 1)
print(example ** 2)
print("Lessdimensional")
example = np.array([[5, 4], [7, 8]])
sep_arr = np.array([2, 3])
print(example / sep_arr)
print(example * sep_arr)
print(example + sep_arr)
print(example - sep_arr)
print(example ** sep_arr)

[2.5 2.  3.5 4. ]
[15 12 21 24]
[37 36 39 40]
[4 3 6 7]
[25 16 49 64]
Multidemensional
[[2.5 2. ]
 [3.5 4. ]]
[[15 12]
 [21 24]]
[[37 36]
 [39 40]]
[[4 3]
 [6 7]]
[[25 16]
 [49 64]]
Lessdimensional
[[2.5        1.33333333]
 [3.5        2.66666667]]
[[10 12]
 [14 24]]
[[ 7  7]
 [ 9 11]]
[[3 1]
 [5 5]]
[[ 25  64]
 [ 49 512]]


In [26]:
#Можно производить стандартные операции над векторами n-мерного пространства
example = np.array([[5, 4], [7, 8]])
print(example.transpose())

[[5 7]
 [4 8]]


In [30]:
#И снова калькулятор
def calculate(a, b=None, func="+"):
    #TODO Ну мы такое уже писали, кажется, совсем просто
    if func == "+":
        return a+b
    if func == "-":
        return a-b
    if func == "**":
        return a**b
    if func == "*":
        return a*b
    if func == "/":
        return a/b
    if func == "T":
        return a.transpose()
    if func == "increment":
        #TODO увеличвает на 1 ДИАГОНАЛЬНЫЕ элементы, если матрица квадратная, иначе возвращает исходную матрицу
        if len(a.shape)==2 and a.shape[0]==a.shape[1]:
            return a+np.eye(a.shape[0])
        return a
    #Примените func ко всем эементам a
    func_vect= np.vectorize(func)
    return func_vect(a)

In [31]:
example = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sample_vec = np.array([2, 4, 10])

assert np.array_equal(calculate(example, sample_vec, "/"), np.array([[ 0.5 ,  0.5 ,  0.3 ], [ 2.  ,  1.25,  0.6 ], [ 3.5 ,  2.  ,  0.9 ]]))
assert np.array_equal(calculate(example, 20, "/"), np.array([[ 0.05,  0.1 ,  0.15],
                                                             [ 0.2 ,  0.25,  0.3 ],
                                                             [ 0.35,  0.4 ,  0.45]]))
assert np.array_equal(calculate(example, 20, "+"), np.array([[21, 22, 23],
                                                             [24, 25, 26],
                                                             [27, 28, 29]]))
assert np.array_equal(calculate(example, sample_vec, "+"), np.array([[ 3,  6, 13],
                                                                     [ 6,  9, 16],
                                                                     [ 9, 12, 19]]))
assert np.array_equal(calculate(example, 20, "*"), np.array([[ 20,  40,  60],
                                                             [ 80, 100, 120],
                                                             [140, 160, 180]]))
assert np.array_equal(calculate(example, sample_vec, "*"), np.array([[ 2,  8, 30],
                                                                     [ 8, 20, 60],
                                                                     [14, 32, 90]]))
assert np.array_equal(calculate(example, 20, "-"), np.array([[-19, -18, -17],
                                                             [-16, -15, -14],
                                                             [-13, -12, -11]]))
assert np.array_equal(calculate(example, sample_vec, "-"), np.array([[-1, -2, -7],
                                                                     [ 2,  1, -4],
                                                                     [ 5,  4, -1]]))
assert np.array_equal(calculate(example, func="T"), np.array([[1, 4, 7],
                                                              [2, 5, 8],
                                                              [3, 6, 9]]))
assert np.array_equal(calculate(example, sample_vec, "**"), np.array([[         1,         16,      59049],
                                                                [        16,        625,   60466176],
                                                                [        49,       4096, 3486784401]]))

#!!!ALARM почему отрицательное число?
assert np.array_equal(calculate(example, 20, "**"), np.array([[                   1,              1048576,           3486784401],
                                                              [       1099511627776,       95367431640625,     3656158440062976],
                                                              [   79792266297612000,  1152921504606846976, -9223372036854775808]]))

assert np.array_equal(calculate(example, func="increment"), np.array([[  2.,   2.,   3.],
                                                                     [  4.,   6.,   6.],
                                                                     [  7.,   8.,  10.]]))
assert np.array_equal(calculate(sample_vec, func="increment"), sample_vec)

AssertionError: 

In [32]:
#Можно считать различные статистикиЮ суммы и другие значения по выбранной оси
example = np.array([[5, 4], [7, 8]])
print(example.sum())
print(example.sum(axis=0))
print(example.sum(axis=1))

#TODO Найти минимум по столбцам, максимум по строкам, среднее значение всей матриц, дисперсию по строкам и аргминимум по строке

24
[12 12]
[ 9 15]


In [33]:
#Методы выбора
example = np.array([[5, 4], [7, 8]])
example[example >= 5]

array([5, 7, 8])

In [34]:
#Просто скалярное произведение
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

In [38]:
#TODO Линейные уравнения можно решать следующим образом: Ax = y, где A-матрица. 
#A^(T)Ax=A^(T)y
#x=(A^(T)A)^(-1)A^(T)y
#давайте сделаю свою решалку таких уравнений
#HINT: np.linalg...
def solution_finder(A, y):
    x=np.dop(np.dot(np.linalg.inv(np.dot(A.T,A)),A.T),y)
    return x


In [ ]:
#TODO решить систему методом Крамера
#HINT: np.linalg.det
def cramer_solver(A, b):
    return

In [ ]:
example = np.array([[5, 4], [7, 8]])
sample_vec = np.array([1, 2])

assert np.allclose(cramer_solver(example, sample_vec), np.array([0.0, 0.25]))

example = np.array([[5, 4, 1], [7, 8, 12], [10, 45, 24]])
sample_vec = np.array([1, 2, 123])

assert np.allclose(cramer_solver(example, sample_vec), np.array([-2.63406011, -3.74012964, -0.79021803]))

In [ ]:
#Быстро сделали. Давайте сделаем решение методом Гаусса. Задание со звездочкой, я за 5 минут не смог написать

# Pandas

In [40]:
import pandas as pd

In [42]:
#Загрузим данные
titanik_excel = pd.read_excel("titanic3.xls")

#dataframe.head(#observ) позволяет взглянуть на первые #observ данных, по умолчанию 5
titanik_excel.head(10)

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
5       1         1                              Anderson, Mr. Harry    male   
6       1         1                Andrews, Miss. Kornelia Theodosia  female   
7       1         0                           Andrews, Mr. Thomas Jr    male   
8       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)  female   
9       1         0                          Artagaveytia, Mr. Ramon    male   

       age  sibsp  parch    ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0     24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2    113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2    113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
5  48.0000      0      0     19952   26.5500      E12        S    3    NaN   
6  63.0000      1      0     13502   77.9583       D7        S   10    NaN   
7  39.0000      0      0    112050    0.0000      A36        S  NaN    NaN   
8  53.0000      2      0     11769   51.4792     C101        S    D    NaN   
9  71.0000      0      0  PC 17609   49.5042      NaN        C  NaN   22.0   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON  
5                     New York, NY  
6                       Hudson, NY  
7                      Belfast, NI  
8              Bayside, Queens, NY  
9              Montevideo, Uruguay

In [50]:
#TODO Загрузите данные из .tsv файла (пример в слайдах!). Посмотрите на перввые 7 строк
titanik_csv = pd.read_csv("titanik.tsv",sep="|")
titanik_csv.head(7)

Unnamed: 0  pclass  survived  \
0           0       1         1   
1           1       1         1   
2           2       1         0   
3           3       1         0   
4           4       1         0   
5           5       1         1   
6           6       1         1   

                                              name     sex      age  sibsp  \
0                    Allen, Miss. Elisabeth Walton  female  29.0000      0   
1                   Allison, Master. Hudson Trevor    male   0.9167      1   
2                     Allison, Miss. Helen Loraine  female   2.0000      1   
3             Allison, Mr. Hudson Joshua Creighton    male  30.0000      1   
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000      1   
5                              Anderson, Mr. Harry    male  48.0000      0   
6                Andrews, Miss. Kornelia Theodosia  female  63.0000      1   

   parch  ticket      fare    cabin embarked boat   body  \
0      0   24160  211.3375       B5        S    2    NaN   
1      2  113781  151.5500  C22 C26        S   11    NaN   
2      2  113781  151.5500  C22 C26        S  NaN    NaN   
3      2  113781  151.5500  C22 C26        S  NaN  135.0   
4      2  113781  151.5500  C22 C26        S  NaN    NaN   
5      0   19952   26.5500      E12        S    3    NaN   
6      0   13502   77.9583       D7        S   10    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON  
5                     New York, NY  
6                       Hudson, NY

In [51]:
titanik_csv['sex'].value_counts()

male      843
female    466
Name: sex, dtype: int64

In [52]:
titanik_csv['body'].isnull().sum()

1188

In [ ]:
#совместная работа
#1. Кого больше мужчин или женщин?
#2. Отделить первую часть имени (до запятой)
#3. Узнать, сколько пропусков в колонке body
#4. Удалить колонку body
#5. Обращение к строке
#6. Разбить возраст на бины
#7. Входит ли Miss в name
#8. Срез по числу parch (сравнение)
#9. Hist по parch

# Flask

In [53]:
%%writefile simple_flask.py

from flask import Flask
app = Flask(__name__)
 
@app.route("/")
def hello():
    return "Hello World!"
 
if __name__ == "__main__":
    app.run()
    
#Теперь нужно запустить, через python simple_flask.py

Writing simple_flask.py


In [ ]:
%%writefile  simple_flask.py

from flask import Flask
app = Flask(__name__)
 
@app.route("/")
def hello():
    return "Hello World!"

@app.route("/members/<string:name>/")
def getMember(name):
    return name

if __name__ == "__main__":
    app.run()
#Теперь нужно запустить, через python simple_flask.py

In [ ]:
#TODO написать сервер, который получает запрос /set_member/name, а по запросу /get_members возвращает всех
#memberов через запятую